# Generated by Django 5.2.4 on 2025-07-22 10:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='NewsSource',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
                ('domain', models.CharField(max_length=255)),
                ('url', models.URLField()),
                ('rss_feed', models.URLField(blank=True, null=True)),
                ('priority', models.IntegerField(default=1)),
                ('is_active', models.BooleanField(default=True)),
                ('language', models.CharField(default='en', max_length=10)),
                ('country', models.CharField(blank=True, max_length=10, null=True)),
                ('crawl_interval', models.IntegerField(default=3600)),
                ('last_crawled', models.DateTimeField(blank=True, null=True)),
                ('next_crawl', models.DateTimeField(blank=True, null=True)),
                ('title_selector', models.CharField(blank=True, max_length=255, null=True)),
                ('content_selector', models.CharField(blank=True, max_length=255, null=True)),
                ('author_selector', models.CharField(blank=True, max_length=255, null=True)),
                ('date_selector', models.CharField(blank=True, max_length=255, null=True)),
                ('image_selector', models.CharField(blank=True, max_length=255, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['priority', 'name'],
            },
        ),
        migrations.CreateModel(
            name='CrawlSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('finished_at', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(choices=[('running', 'Running'), ('completed', 'Completed'), ('failed', 'Failed'), ('cancelled', 'Cancelled')], default='running', max_length=20)),
                ('articles_found', models.IntegerField(default=0)),
                ('articles_saved', models.IntegerField(default=0)),
                ('errors', models.TextField(blank=True, null=True)),
                ('source', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='crawlers.newssource')),
            ],
            options={
                'ordering': ['-started_at'],
            },
        ),
    ]
