# Generated by Django 5.2.4 on 2025-07-22 10:19

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='NewsArticle',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('article_id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('title', models.CharField(blank=True, max_length=255, null=True)),
                ('link', models.TextField(blank=True, null=True, unique=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('content', models.TextField(blank=True, null=True)),
                ('pub_date', models.DateTimeField(blank=True, null=True)),
                ('image_url', models.TextField(blank=True, null=True)),
                ('video_url', models.CharField(blank=True, max_length=255, null=True)),
                ('source_id', models.CharField(blank=True, max_length=255, null=True)),
                ('source_name', models.CharField(blank=True, max_length=255, null=True)),
                ('source_priority', models.BigIntegerField(blank=True, null=True)),
                ('keywords', models.TextField(blank=True, default='[]')),
                ('creator', models.TextField(blank=True, default='[]')),
                ('country', models.TextField(blank=True, default='[]')),
                ('category', models.TextField(blank=True, default='[]')),
                ('topics', models.TextField(blank=True, default='[]')),
                ('language', models.CharField(blank=True, max_length=20, null=True)),
                ('entities', models.TextField(blank=True, default='[]', null=True)),
                ('sentiment', models.CharField(blank=True, max_length=50, null=True)),
                ('sentiment_score', models.FloatField(blank=True, null=True)),
                ('embedding', models.TextField(blank=True, null=True)),
                ('content_hash', models.CharField(blank=True, max_length=64, null=True, unique=True)),
                ('processing_status', models.CharField(choices=[('raw', 'Raw'), ('processed', 'Processed'), ('error', 'Error')], default='raw', max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'news_articles',
                'ordering': ['-pub_date', '-created_at'],
                'indexes': [models.Index(fields=['pub_date'], name='news_articl_pub_dat_a104e3_idx'), models.Index(fields=['source_id'], name='news_articl_source__b953f8_idx'), models.Index(fields=['processing_status'], name='news_articl_process_a27af7_idx'), models.Index(fields=['language'], name='news_articl_languag_ad109d_idx'), models.Index(fields=['sentiment'], name='news_articl_sentime_18983e_idx')],
            },
        ),
    ]
