-- Django Models DDL
-- Generated from Django models

BEGIN;
--
-- Create model User
--
CREATE TABLE "user" ("id" bigint NOT NULL PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY, "password" varchar(128) NOT NULL, "last_login" timestamp with time zone NULL, "is_superuser" boolean NOT NULL, "first_name" varchar(150) NOT NULL, "last_name" varchar(150) NOT NULL, "is_staff" boolean NOT NULL, "is_active" boolean NOT NULL, "date_joined" timestamp with time zone NOT NULL, "fname" varchar(255) NOT NULL, "lname" varchar(255) NOT NULL, "address" varchar(255) NULL, "age" timestamp with time zone NULL, "phone" varchar(255) NULL, "image" varchar(255) NULL, "language" varchar(10) NULL, "country" varchar(10) NULL, "username" varchar(150) NULL UNIQUE, "email" varchar(254) NOT NULL UNIQUE);
CREATE TABLE "user_groups" ("id" bigint NOT NULL PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY, "user_id" bigint NOT NULL, "group_id" integer NOT NULL);
CREATE TABLE "user_user_permissions" ("id" bigint NOT NULL PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY, "user_id" bigint NOT NULL, "permission_id" integer NOT NULL);
--
-- Create model Session
--
CREATE TABLE "session" ("id" bigint NOT NULL PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY, "device" varchar(255) NULL, "ip" varchar(255) NULL, "token" text NULL, "created_at" timestamp with time zone NULL, "updated_at" timestamp with time zone NULL, "deleted_at" timestamp with time zone NULL, "user_id" bigint NOT NULL);
--
-- Create model Post
--
CREATE TABLE "posts" ("id" bigint NOT NULL PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY, "article_id" uuid NOT NULL UNIQUE, "title" varchar(500) NULL, "link" text NULL UNIQUE, "description" text NULL, "content" text NULL, "pub_date" timestamp with time zone NULL, "language" varchar(10) NULL, "image_url" text NULL, "video_url" text NULL, "source_name" varchar(255) NULL, "source_domain" varchar(255) NULL, "source_country" varchar(10) NULL, "source_language" varchar(10) NULL, "author" varchar(255) NULL, "creator" jsonb NOT NULL, "category" jsonb NOT NULL, "tags" jsonb NOT NULL, "keywords" jsonb NOT NULL, "country" jsonb NOT NULL, "region" jsonb NOT NULL, "city" jsonb NOT NULL, "sentiment" varchar(50) NULL, "sentiment_score" double precision NULL, "readability_score" double precision NULL, "word_count" integer NULL, "content_hash" varchar(64) NULL UNIQUE, "processing_status" varchar(50) NULL, "quality_score" double precision NULL, "crawl_type" varchar(20) NULL, "spider_name" varchar(100) NULL, "feed_url" text NULL, "source_id" varchar(255) NULL, "source_priority" bigint NULL, "pubDate" timestamp with time zone NULL, "entities" jsonb NULL, "embedding" jsonb NULL, "topics" jsonb NOT NULL, "crawled_at" timestamp with time zone NULL, "created_at" timestamp with time zone NULL, "updated_at" timestamp with time zone NULL, "deleted_at" timestamp with time zone NULL);
--
-- Create model NewsSource
--
CREATE TABLE "news_sources" ("id" bigint NOT NULL PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY, "name" varchar(255) NOT NULL, "domain" varchar(255) NOT NULL, "country_code" varchar(10) NOT NULL, "country_name" varchar(255) NOT NULL, "language" varchar(10) NOT NULL, "rss_feeds" jsonb NOT NULL, "is_active" boolean NOT NULL, "created_at" timestamp with time zone NOT NULL, "updated_at" timestamp with time zone NOT NULL);
--
-- Create model CrawlJob
--
CREATE TABLE "crawl_jobs" ("id" bigint NOT NULL PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY, "job_id" uuid NOT NULL UNIQUE, "status" varchar(20) NOT NULL, "started_at" timestamp with time zone NULL, "completed_at" timestamp with time zone NULL, "articles_found" integer NOT NULL, "articles_processed" integer NOT NULL, "error_message" text NULL, "created_at" timestamp with time zone NOT NULL, "updated_at" timestamp with time zone NOT NULL, "source_id" bigint NOT NULL);
--
-- Create model Auth
--
CREATE TABLE "auth" ("id" bigint NOT NULL PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY, "token" text NULL, "refresh_token" text NULL, "expires_at" timestamp with time zone NULL, "created_at" timestamp with time zone NULL, "updated_at" timestamp with time zone NULL, "user_id" bigint NOT NULL);
--
-- Create model Immotion
--
CREATE TABLE "immotion" ("id" bigint NOT NULL PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY, "comment" text NULL, "like" integer NULL, "shared" boolean NULL, "post_id" bigint NOT NULL, "user_id" bigint NOT NULL);
CREATE INDEX "user_username_cf016618_like" ON "user" ("username" varchar_pattern_ops);
CREATE INDEX "user_email_54dc62b2_like" ON "user" ("email" varchar_pattern_ops);
ALTER TABLE "user_groups" ADD CONSTRAINT "user_groups_user_id_group_id_40beef00_uniq" UNIQUE ("user_id", "group_id");
ALTER TABLE "user_groups" ADD CONSTRAINT "user_groups_user_id_abaea130_fk_user_id" FOREIGN KEY ("user_id") REFERENCES "user" ("id") DEFERRABLE INITIALLY DEFERRED;
ALTER TABLE "user_groups" ADD CONSTRAINT "user_groups_group_id_b76f8aba_fk_auth_group_id" FOREIGN KEY ("group_id") REFERENCES "auth_group" ("id") DEFERRABLE INITIALLY DEFERRED;
CREATE INDEX "user_groups_user_id_abaea130" ON "user_groups" ("user_id");
CREATE INDEX "user_groups_group_id_b76f8aba" ON "user_groups" ("group_id");
ALTER TABLE "user_user_permissions" ADD CONSTRAINT "user_user_permissions_user_id_permission_id_7dc6e2e0_uniq" UNIQUE ("user_id", "permission_id");
ALTER TABLE "user_user_permissions" ADD CONSTRAINT "user_user_permissions_user_id_ed4a47ea_fk_user_id" FOREIGN KEY ("user_id") REFERENCES "user" ("id") DEFERRABLE INITIALLY DEFERRED;
ALTER TABLE "user_user_permissions" ADD CONSTRAINT "user_user_permission_permission_id_9deb68a3_fk_auth_perm" FOREIGN KEY ("permission_id") REFERENCES "auth_permission" ("id") DEFERRABLE INITIALLY DEFERRED;
CREATE INDEX "user_user_permissions_user_id_ed4a47ea" ON "user_user_permissions" ("user_id");
CREATE INDEX "user_user_permissions_permission_id_9deb68a3" ON "user_user_permissions" ("permission_id");
ALTER TABLE "session" ADD CONSTRAINT "session_user_id_65cb3187_fk_user_id" FOREIGN KEY ("user_id") REFERENCES "user" ("id") DEFERRABLE INITIALLY DEFERRED;
CREATE INDEX "session_user_id_65cb3187" ON "session" ("user_id");
CREATE INDEX "posts_link_5a13d354_like" ON "posts" ("link" text_pattern_ops);
CREATE INDEX "posts_content_hash_3a5c013f_like" ON "posts" ("content_hash" varchar_pattern_ops);
CREATE INDEX "posts_pub_dat_dc4cb5_idx" ON "posts" ("pub_date");
CREATE INDEX "posts_source__4fc22c_idx" ON "posts" ("source_country");
CREATE INDEX "posts_languag_b3b925_idx" ON "posts" ("language");
CREATE INDEX "posts_crawl_t_5661b7_idx" ON "posts" ("crawl_type");
CREATE INDEX "posts_process_99799f_idx" ON "posts" ("processing_status");
CREATE INDEX "posts_created_060265_idx" ON "posts" ("created_at");
CREATE INDEX "posts_crawled_c7cea2_idx" ON "posts" ("crawled_at");
ALTER TABLE "news_sources" ADD CONSTRAINT "news_sources_domain_country_code_c4dd1132_uniq" UNIQUE ("domain", "country_code");
ALTER TABLE "crawl_jobs" ADD CONSTRAINT "crawl_jobs_source_id_323980a5_fk_news_sources_id" FOREIGN KEY ("source_id") REFERENCES "news_sources" ("id") DEFERRABLE INITIALLY DEFERRED;
CREATE INDEX "crawl_jobs_source_id_323980a5" ON "crawl_jobs" ("source_id");
ALTER TABLE "auth" ADD CONSTRAINT "auth_user_id_bf32149c_fk_user_id" FOREIGN KEY ("user_id") REFERENCES "user" ("id") DEFERRABLE INITIALLY DEFERRED;
CREATE INDEX "auth_user_id_bf32149c" ON "auth" ("user_id");
ALTER TABLE "immotion" ADD CONSTRAINT "immotion_user_id_post_id_f767f109_uniq" UNIQUE ("user_id", "post_id");
ALTER TABLE "immotion" ADD CONSTRAINT "immotion_post_id_f5e83538_fk_posts_id" FOREIGN KEY ("post_id") REFERENCES "posts" ("id") DEFERRABLE INITIALLY DEFERRED;
ALTER TABLE "immotion" ADD CONSTRAINT "immotion_user_id_8ca000df_fk_user_id" FOREIGN KEY ("user_id") REFERENCES "user" ("id") DEFERRABLE INITIALLY DEFERRED;
CREATE INDEX "immotion_post_id_f5e83538" ON "immotion" ("post_id");
CREATE INDEX "immotion_user_id_8ca000df" ON "immotion" ("user_id");
CREATE INDEX "userPost" ON "immotion" ("user_id", "post_id");
COMMIT;
