# Generated by Django 4.2.7 on 2025-07-23 10:03

import django.contrib.postgres.fields
from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):
    dependencies = [
        ("news", "0002_post"),
    ]

    operations = [
        migrations.CreateModel(
            name="CrawlLog",
            fields=[
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                ("spider_name", models.CharField(max_length=100)),
                ("country_code", models.CharField(max_length=10)),
                ("source_domain", models.CharField(max_length=255)),
                ("crawl_type", models.CharField(max_length=20)),
                ("start_time", models.DateTimeField()),
                ("end_time", models.DateTimeField(blank=True, null=True)),
                ("duration_seconds", models.FloatField(blank=True, null=True)),
                ("articles_found", models.IntegerField(default=0)),
                ("articles_saved", models.IntegerField(default=0)),
                ("articles_skipped", models.IntegerField(default=0)),
                ("errors_count", models.IntegerField(default=0)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("running", "Running"),
                            ("completed", "Completed"),
                            ("failed", "Failed"),
                            ("cancelled", "Cancelled"),
                        ],
                        default="running",
                        max_length=20,
                    ),
                ),
                ("error_message", models.TextField(blank=True, null=True)),
                ("error_traceback", models.TextField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "db_table": "crawl_log",
            },
        ),
        migrations.CreateModel(
            name="CrawlSchedule",
            fields=[
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                ("country_code", models.CharField(max_length=10)),
                ("source_domain", models.CharField(max_length=255)),
                (
                    "crawl_type",
                    models.CharField(
                        choices=[("historical", "Historical"), ("live", "Live")],
                        default="live",
                        max_length=20,
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                ("interval_minutes", models.IntegerField(default=15)),
                ("last_crawl", models.DateTimeField(blank=True, null=True)),
                ("next_crawl", models.DateTimeField(blank=True, null=True)),
                ("total_articles", models.IntegerField(default=0)),
                ("success_count", models.IntegerField(default=0)),
                ("error_count", models.IntegerField(default=0)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "db_table": "crawl_schedule",
            },
        ),
        migrations.AddField(
            model_name="post",
            name="author",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="post",
            name="city",
            field=django.contrib.postgres.fields.ArrayField(
                base_field=models.TextField(), blank=True, default=list, size=None
            ),
        ),
        migrations.AddField(
            model_name="post",
            name="crawl_type",
            field=models.CharField(
                choices=[("historical", "Historical"), ("live", "Live")],
                default="live",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="post",
            name="crawled_at",
            field=models.DateTimeField(
                auto_now_add=True, default=django.utils.timezone.now
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="post",
            name="feed_url",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="post",
            name="language",
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name="post",
            name="quality_score",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="post",
            name="readability_score",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="post",
            name="region",
            field=django.contrib.postgres.fields.ArrayField(
                base_field=models.TextField(), blank=True, default=list, size=None
            ),
        ),
        migrations.AddField(
            model_name="post",
            name="sentiment",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name="post",
            name="sentiment_score",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="post",
            name="source_country",
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name="post",
            name="source_domain",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="post",
            name="source_language",
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name="post",
            name="spider_name",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="post",
            name="tags",
            field=django.contrib.postgres.fields.ArrayField(
                base_field=models.TextField(), blank=True, default=list, size=None
            ),
        ),
        migrations.AddField(
            model_name="post",
            name="video_url",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="post",
            name="word_count",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="post",
            name="processing_status",
            field=models.CharField(
                choices=[
                    ("raw", "Raw"),
                    ("processed", "Processed"),
                    ("error", "Error"),
                    ("filtered", "Filtered"),
                ],
                default="raw",
                max_length=50,
            ),
        ),
        migrations.AddIndex(
            model_name="post",
            index=models.Index(fields=["pub_date"], name="posts_pub_dat_dc4cb5_idx"),
        ),
        migrations.AddIndex(
            model_name="post",
            index=models.Index(
                fields=["source_country"], name="posts_source__4fc22c_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="post",
            index=models.Index(fields=["language"], name="posts_languag_b3b925_idx"),
        ),
        migrations.AddIndex(
            model_name="post",
            index=models.Index(fields=["crawl_type"], name="posts_crawl_t_5661b7_idx"),
        ),
        migrations.AddIndex(
            model_name="post",
            index=models.Index(
                fields=["processing_status"], name="posts_process_99799f_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="post",
            index=models.Index(fields=["created_at"], name="posts_created_060265_idx"),
        ),
        migrations.AlterUniqueTogether(
            name="crawlschedule",
            unique_together={("country_code", "source_domain", "crawl_type")},
        ),
        migrations.AddIndex(
            model_name="crawllog",
            index=models.Index(
                fields=["spider_name"], name="crawl_log_spider__bb93f9_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="crawllog",
            index=models.Index(
                fields=["country_code"], name="crawl_log_country_a315e2_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="crawllog",
            index=models.Index(
                fields=["crawl_type"], name="crawl_log_crawl_t_a44630_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="crawllog",
            index=models.Index(
                fields=["start_time"], name="crawl_log_start_t_bb05c2_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="crawllog",
            index=models.Index(fields=["status"], name="crawl_log_status_aee0d2_idx"),
        ),
    ]
