# Generated by Django 4.2.7 on 2025-07-28 14:45

from django.conf import settings
import django.contrib.auth.models
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import uuid


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("auth", "0012_alter_user_first_name_max_length"),
    ]

    operations = [
        migrations.CreateModel(
            name="User",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("password", models.CharField(max_length=128, verbose_name="password")),
                (
                    "last_login",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="last login"
                    ),
                ),
                (
                    "is_superuser",
                    models.BooleanField(
                        default=False,
                        help_text="Designates that this user has all permissions without explicitly assigning them.",
                        verbose_name="superuser status",
                    ),
                ),
                (
                    "first_name",
                    models.CharField(
                        blank=True, max_length=150, verbose_name="first name"
                    ),
                ),
                (
                    "last_name",
                    models.CharField(
                        blank=True, max_length=150, verbose_name="last name"
                    ),
                ),
                (
                    "is_staff",
                    models.BooleanField(
                        default=False,
                        help_text="Designates whether the user can log into this admin site.",
                        verbose_name="staff status",
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        default=True,
                        help_text="Designates whether this user should be treated as active. Unselect this instead of deleting accounts.",
                        verbose_name="active",
                    ),
                ),
                (
                    "date_joined",
                    models.DateTimeField(
                        default=django.utils.timezone.now, verbose_name="date joined"
                    ),
                ),
                ("fname", models.CharField(blank=True, default="", max_length=255)),
                ("lname", models.CharField(blank=True, default="", max_length=255)),
                ("address", models.CharField(blank=True, max_length=255, null=True)),
                ("age", models.DateTimeField(blank=True, null=True)),
                ("phone", models.CharField(blank=True, max_length=255, null=True)),
                ("image", models.CharField(blank=True, max_length=255, null=True)),
                ("language", models.CharField(blank=True, max_length=10, null=True)),
                ("country", models.CharField(blank=True, max_length=10, null=True)),
                (
                    "username",
                    models.CharField(
                        blank=True, max_length=150, null=True, unique=True
                    ),
                ),
                ("email", models.EmailField(max_length=254, unique=True)),
                (
                    "groups",
                    models.ManyToManyField(
                        blank=True,
                        help_text="The groups this user belongs to. A user will get all permissions granted to each of their groups.",
                        related_name="user_set",
                        related_query_name="user",
                        to="auth.group",
                        verbose_name="groups",
                    ),
                ),
                (
                    "user_permissions",
                    models.ManyToManyField(
                        blank=True,
                        help_text="Specific permissions for this user.",
                        related_name="user_set",
                        related_query_name="user",
                        to="auth.permission",
                        verbose_name="user permissions",
                    ),
                ),
            ],
            options={
                "verbose_name": "User",
                "verbose_name_plural": "Users",
                "db_table": "user",
            },
            managers=[
                ("objects", django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name="Session",
            fields=[
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                ("device", models.CharField(blank=True, max_length=255, null=True)),
                ("ip", models.CharField(blank=True, max_length=255, null=True)),
                ("token", models.TextField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True, null=True)),
                ("updated_at", models.DateTimeField(auto_now=True, null=True)),
                ("deleted_at", models.DateTimeField(blank=True, null=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="sessions",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Session",
                "verbose_name_plural": "Sessions",
                "db_table": "session",
            },
        ),
        migrations.CreateModel(
            name="Post",
            fields=[
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                (
                    "article_id",
                    models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
                ),
                ("title", models.CharField(blank=True, max_length=500, null=True)),
                ("link", models.TextField(blank=True, null=True, unique=True)),
                ("description", models.TextField(blank=True, null=True)),
                ("content", models.TextField(blank=True, null=True)),
                ("pub_date", models.DateTimeField(blank=True, null=True)),
                ("language", models.CharField(blank=True, max_length=10, null=True)),
                ("image_url", models.TextField(blank=True, null=True)),
                ("video_url", models.TextField(blank=True, null=True)),
                (
                    "source_name",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "source_domain",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "source_country",
                    models.CharField(blank=True, max_length=10, null=True),
                ),
                (
                    "source_language",
                    models.CharField(blank=True, max_length=10, null=True),
                ),
                ("author", models.CharField(blank=True, max_length=255, null=True)),
                ("creator", models.JSONField(blank=True, default=list)),
                ("category", models.JSONField(blank=True, default=list)),
                ("tags", models.JSONField(blank=True, default=list)),
                ("keywords", models.JSONField(blank=True, default=list)),
                ("country", models.JSONField(blank=True, default=list)),
                ("region", models.JSONField(blank=True, default=list)),
                ("city", models.JSONField(blank=True, default=list)),
                ("sentiment", models.CharField(blank=True, max_length=50, null=True)),
                ("sentiment_score", models.FloatField(blank=True, null=True)),
                ("readability_score", models.FloatField(blank=True, null=True)),
                ("word_count", models.IntegerField(blank=True, null=True)),
                (
                    "content_hash",
                    models.CharField(blank=True, max_length=64, null=True, unique=True),
                ),
                (
                    "processing_status",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("raw", "Raw"),
                            ("processed", "Processed"),
                            ("error", "Error"),
                            ("filtered", "Filtered"),
                        ],
                        default="raw",
                        max_length=50,
                        null=True,
                    ),
                ),
                ("quality_score", models.FloatField(blank=True, null=True)),
                (
                    "crawl_type",
                    models.CharField(
                        blank=True,
                        choices=[("historical", "Historical"), ("live", "Live")],
                        default="live",
                        max_length=20,
                        null=True,
                    ),
                ),
                (
                    "spider_name",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                ("feed_url", models.TextField(blank=True, null=True)),
                ("source_id", models.CharField(blank=True, max_length=255, null=True)),
                ("source_priority", models.BigIntegerField(blank=True, null=True)),
                ("pubDate", models.DateTimeField(blank=True, null=True)),
                ("entities", models.JSONField(blank=True, null=True)),
                ("embedding", models.JSONField(blank=True, null=True)),
                ("topics", models.JSONField(blank=True, default=list)),
                ("crawled_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True, null=True)),
                ("updated_at", models.DateTimeField(auto_now=True, null=True)),
                ("deleted_at", models.DateTimeField(blank=True, null=True)),
            ],
            options={
                "verbose_name": "Post",
                "verbose_name_plural": "Posts",
                "db_table": "posts",
                "indexes": [
                    models.Index(fields=["pub_date"], name="posts_pub_dat_dc4cb5_idx"),
                    models.Index(
                        fields=["source_country"], name="posts_source__4fc22c_idx"
                    ),
                    models.Index(fields=["language"], name="posts_languag_b3b925_idx"),
                    models.Index(
                        fields=["crawl_type"], name="posts_crawl_t_5661b7_idx"
                    ),
                    models.Index(
                        fields=["processing_status"], name="posts_process_99799f_idx"
                    ),
                    models.Index(
                        fields=["created_at"], name="posts_created_060265_idx"
                    ),
                    models.Index(
                        fields=["crawled_at"], name="posts_crawled_c7cea2_idx"
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="NewsSource",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("domain", models.CharField(max_length=255)),
                ("country_code", models.CharField(max_length=10)),
                ("country_name", models.CharField(max_length=255)),
                ("language", models.CharField(max_length=10)),
                ("rss_feeds", models.JSONField(default=list)),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "News Source",
                "verbose_name_plural": "News Sources",
                "db_table": "news_sources",
                "unique_together": {("domain", "country_code")},
            },
        ),
        migrations.CreateModel(
            name="CrawlJob",
            fields=[
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                (
                    "job_id",
                    models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("running", "Running"),
                            ("completed", "Completed"),
                            ("failed", "Failed"),
                            ("cancelled", "Cancelled"),
                        ],
                        default="pending",
                        max_length=20,
                    ),
                ),
                ("started_at", models.DateTimeField(blank=True, null=True)),
                ("completed_at", models.DateTimeField(blank=True, null=True)),
                ("articles_found", models.IntegerField(default=0)),
                ("articles_processed", models.IntegerField(default=0)),
                ("error_message", models.TextField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "source",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="crawl_jobs",
                        to="twitto_models.newssource",
                    ),
                ),
            ],
            options={
                "verbose_name": "Crawl Job",
                "verbose_name_plural": "Crawl Jobs",
                "db_table": "crawl_jobs",
            },
        ),
        migrations.CreateModel(
            name="Auth",
            fields=[
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                ("token", models.TextField(blank=True, null=True)),
                ("refresh_token", models.TextField(blank=True, null=True)),
                ("expires_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True, null=True)),
                ("updated_at", models.DateTimeField(auto_now=True, null=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="auths",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Auth",
                "verbose_name_plural": "Auths",
                "db_table": "auth",
            },
        ),
        migrations.CreateModel(
            name="Immotion",
            fields=[
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                ("comment", models.TextField(blank=True, null=True)),
                ("like", models.IntegerField(blank=True, default=0, null=True)),
                ("shared", models.BooleanField(blank=True, default=False, null=True)),
                (
                    "post",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="immotions",
                        to="twitto_models.post",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="immotions",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Immotion",
                "verbose_name_plural": "Imotions",
                "db_table": "immotion",
                "indexes": [models.Index(fields=["user", "post"], name="userPost")],
                "unique_together": {("user", "post")},
            },
        ),
    ]
